### ISSUE TITLE
Some Icons have no coherent font size or white space at top or bottom

### ISSUE THREAD

**Issue by offtherailz** [geosolutions-it/MapStore2-theme#52]
The size of the icons is not coherent for all the icons with the same font size. 
Somewere, like in  `eye-close` and `eye-open` icons for instance, there are white spaces on top and bottom that doesn't allow to use them correctly.

See in red the border of the span that contains the char. it causes line breaks. 
![image](https://cloud.githubusercontent.com/assets/1279510/16235531/858fa5dc-37d5-11e6-8a07-d5c9068353a3.png)

The eye have 35px font size while the folder is 23px

**Comment by offtherailz** [comment]
Same for the icons `adjust`, `list` and more over...

**Comment by andreabiagi** [comment]
Yes, we already know. We have to export a new svg and resize the icons inside fon .
I'm going to  update the new font soon.
Do you need other icons?

**Comment by offtherailz** [comment]
in the meantime we are working on the file ms2-theme.css, that includes the needed parts of css that make the theme (general instead are loaded by default by MapStore2). You should check the font-sizes on that file when you change the theme. 
About the missing icons, from our current usage only "Upload File" is missing.

**Comment by offtherailz** [comment]
to check, the current URL for the demo with the correct integration of the theme is this:
http://qa.mapstore2.geo-solutions.it/mapstore/themed.html?localConfig=localConfig-themed#/viewer/leaflet/0
NOTE: Wait around 30 after the latest commit on MapStore2 minutes to see the latest changes.
