### ISSUE TITLE
Missing thumbnails

### ISSUE THREAD

**Issue by simboss** [geosolutions-it/MapStore2-theme#72]
With the latest merge new items were added but their thumbnail in the home page is missing.

**Comment by andreabiagi** [comment]
Do you miss these thumbnails?
![thumbs_miss](https://cloud.githubusercontent.com/assets/18553566/16725589/3e81d9f2-4758-11e6-858d-1e7afe3d70bb.JPG)

**Comment by offtherailz** [comment]
Take a look at this: 
http://lf.mapstore2.geo-solutions.it/samples/

**Comment by andreabiagi** [comment]
i think because they are .JPG instead of .jpg. 
I have to send them again?
![image](https://cloud.githubusercontent.com/assets/18553566/16762337/6031581c-4824-11e6-9d70-f334c3db9a0b.png)

**Comment by offtherailz** [comment]
Ok, this is because windows is case insensitive. 
Take a look at this about how to fix the issue. http://stackoverflow.com/questions/1793735/change-case-of-a-file-on-windows

**Comment by offtherailz** [comment]
And take this chance to fix also the map.jpg background that is not visible in the mock-ups
