### ISSUE TITLE
Default button size is too large

### ISSUE THREAD

**Issue by offtherailz** [geosolutions-it/MapStore2-theme#75]
and it is equal to btn-lg. We should reduce the font size for default buttons.

**Comment by andreabiagi** [comment]
when you talk about default buttons mean md-btn size? 
I can't reduce font size too much. I prefer maintain the proportion between buttons. 
I suggest to use always btn-sm. 

I prepare a new pull request with new btn-md size and Home.html changes ( editing map tools http://lf.mapstore2.geo-solutions.it/samples/map/home.html)?

**Comment by MV88** [comment]
Hi @offtherailz and @andreabiagi I just looked at the PR #84 and I have some comments about.

Reducing the size of the default button can lead to some problems in the UI. Therefore I need to check all the tools that use default button size (btn class). 
I noticed that if we want to reduce the size of the save and delete map buttons we can just remove the btn-lg class as showed in the following picture. 
![image](https://cloud.githubusercontent.com/assets/11991428/17852969/4b233f10-686a-11e6-80e4-096cb26e6340.png)

In the carousel the open button uses the default size. Do you want to make it bigger by using the btn-lg size?

**Comment by andreabiagi** [comment]
I prefer btn-lg size in the carousel. 
Check the color. Now it isn't the primary button color. 
http://dev.mapstore2.geo-solutions.it/mapstore/#/?_k=7wgt5u

**Comment by Gnafu** [comment]
Closing this, as it is fixed by PR #84
